#define ENGINE_VERSION_MAJOR "0"
#define ENGINE_VERSION_MINOR "0"
#define ENGINE_VERSION_PATCH "1"
#define ENGINE_VERSION_EXTRA ""
#define ENGINE_VERSION "0.0"
#define ENGINE_VERSION_FULL "0.0.1"

#define _VG_PLOG_ID 201
#define _VG_VULKAN_PLOG_ID 202
#define _VG_COST_TIME_PLOG_ID 203
#define VG_ENABLE_VALIDATION_LAYERS
/* #undef VG_ENABLE_COST_TIMER */
